### PR TITLE
Add andino IMU

### PR DESCRIPTION
**Pull request by ivanpauno**
# 🎉 New feature

Adds IMU support. Realtes to #50 

## Summary

Requires #215 into firmware.

This is only  configures broadcasting from ROS control.
More details:
 * Adds simulation
 * Modifies diff drive and andino base
 * Adds imu to urdf

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by ivanpauno** [comment]
@gonzodepedro I think you need to push your changes for simulation and URDF to this branch.

**Comment by ivanpauno** [comment]
I will fix linters and DCO sometime this week.
If I don't have time, I can take a look after my Vacations (i.e. on January) if it's still pending.

**Comment by gonzodepedro** [comment]
> @gonzodepedro I think you need to push your changes for simulation and URDF to this branch.

Fixed

**Comment by jballoffet** [comment]
@ivanpauno, now that https://github.com/Ekumen-OS/andino/pull/215 has been merged, I would like to lend a hand here so as to have this PR submitted as well.

In order to do so (and avoid losing your contributions), could you please extract the changes to `andino_base` package and have them pushed to `ivanpauno/add-imu-support-to-base-pkg`? Please notice I have created said branch on this repo so as to be able to lend a hand by pushing changes to it.

Thanks!

**Comment by jballoffet** [comment]
Changes added to [ivanpauno/add-imu-support-to-base-pkg](https://github.com/Ekumen-OS/andino/tree/ivanpauno/add-imu-support-to-base-pkg) branch on https://github.com/Ekumen-OS/andino/pull/265.

**Pull request closed without merging**
