### PR TITLE
Fix media link

### PR DESCRIPTION
**Pull request by marcoshuck**
# 🦟 Bug fix

## Summary
The media section contains an emoji that disables auto-scroll when using a link right after the logo. This PR removes the emoji to re-enable auto-scrolling when clicking on the link.

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by francocipollone** [comment]
Nice catch. Can we replace it with another emoji? :pray:

**Comment by marcoshuck** [comment]
> Nice catch. Can we replace it with another emoji? 🙏

It seems emojis break links, I'd recommend we no longer use them

**Comment by jballoffet** [comment]
@marcoshuck please bear in mind that you will need to sign the commits as well to make the DCO check pass. Thanks!

**Comment by marcoshuck** [comment]
> @marcoshuck just in case, have you tried by replacing the link with `https://github.com/Ekumen-OS/andino#selfie-media`? I get the page to auto-scroll when doing so on my end.

Thanks for the comment Javi, I only tried with relative links using the following notation:

```
[Text](README.md#section)
```

I don't think it will be a good idea to use absolute links instead, plus the `selfie-` prefix kind of ruins accessibility and UX.

**Comment by jballoffet** [comment]
> > @marcoshuck just in case, have you tried by replacing the link with `https://github.com/Ekumen-OS/andino#selfie-media`? I get the page to auto-scroll when doing so on my end.
> 
> Thanks for the comment Javi, I only tried with relative links using the following notation:
> 
> ```
> [Text](README.md#section)
> ```
> 
> I don't think it will be a good idea to use absolute links instead, plus the `selfie-` prefix kind of ruins accessibility and UX.

Got it, thanks @marcoshuck for the info!

As a trade off between usability and look&feel, I propose we add a one-line subtitle below each section (similarly to https://github.com/fffaraz/awesome-cpp#standard-libraries), and move the emojis to said line. For instance, for the "Installation" section, something catchy along the lines of "Installing the required software on your Andino" or "How to install the required software on your Andino", plus the emoji.

@francocipollone WDYT?

**Comment by jballoffet** [comment]
> Thanks @marcoshuck for the proposal and @jballoffet for the comments.
> 
> We simply need to do [this](https://github.com/Ekumen-OS/andino/compare/humble...francocipollone/test_link) in order to solve the media link. Replace this
> 
> ```
> _Note: For videos go to [Media](#media) section._
> ```
> 
> By this.
> 
> ```
> _Note: For videos go to [Media](#selfie-media) section._
> ```
> 
> I personally believe that the use of the emojis improves the user readability. I don't really see the necessity of changing this after fixing the media link with the aforementioned suggestion.

Sorry, I understood that fixing the relative links wasn't an option here (didn't give it a try on my end, sorry!). If so, I withdraw my previous proposal and I support @francocipollone's proposal on fixing them instead of removing the emojis.

**Comment by marcoshuck** [comment]
> We simply need to do [this](https://github.com/Ekumen-OS/andino/compare/humble...francocipollone/test_link) in order to solve the media link.

Strange, when I tried it out on my end, it didn't work. Happy to know it's working for you.

**Comment by marcoshuck** [comment]
> I personally believe that the use of the emojis improves the user readability. I don't really see the necessity of changing this after fixing the media link with the aforementioned suggestion.

That's only true if you don't have any reading disability and don't need to use a screen reader.

When using the Accesibility tools in Chrome, the title reads: Mechanical Arm Installation.

**Comment by francocipollone** [comment]
> > I personally believe that the use of the emojis improves the user readability. I don't really see the necessity of changing this after fixing the media link with the aforementioned suggestion.
> 
> That's only true if you don't have any reading disability and/or don't need to use a screen reader.
> 
> When using the Accesibility tools in Chrome, the `Installation` title reads: Mechanical Arm Installation. I'd suggest we move towards being more accessible and remove emojis altogether.
> 
> Also considering that having a link that reads: github.com/[...]/something#selfie-media, it's not precisely informative, but I agree it's my personal opinion.
> 
> We can close this PR.

Your point is valid and we will consider this to be discussed along with @jballoffet .

Thanks for contributing @marcoshuck :rocket:

**Pull request closed without merging**
