### PR TITLE
Remove andino_gz_classic and andino_apps references

### PR DESCRIPTION
**Pull request by JesusSilvaUtrera**
# 🎉 New feature

This is part of the migration to Jazzy

## Summary
This PR is just a simple modification removing the references to `andino_gz_classic` (deprecated because there is no support on ubuntu 24 for Gazebo Classic) and `andino_apps` (no reason to keep it, demos will be stored somewhere else).

## Test it
Take a look at the changes.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by JesusSilvaUtrera** [comment]
@francocipollone @jballoffet This is the first one of the 2 PRs to complete the initial Jazzy migration. This shouldn't need too much time to review, the other one is where we will need to test with the robot.

**Comment by JesusSilvaUtrera** [comment]
When this PR is merged I will open the other one, I still need to try it locally with the new rebase.

**Review by francocipollone — APPROVED** [review]
LGTM

**Review by jballoffet — APPROVED** [review]
LGTM!

**Pull request merged**
