### PR TITLE
Fixed wheel diameter in URDF

### PR DESCRIPTION
**Pull request by JesusSilvaUtrera**
This is just a test pull request to start getting used to the workflow, just changed the value of the wheel diameter to be coherent with the wheel radius in the YAML.

I have reviewed other modules and there is n sense in loading the YAML into the URDF because none of the paramters in it are used in this xacro file, so regarding that this is the only place the wheel_diameter is used it would not be bad to hardcode it.

### CODE REVIEW

**Review by jballoffet — CHANGES_REQUESTED** [review]
Thanks @JesusSilvaUtrera for contributing to Andino!

Please notice that the DCO check is failing because the commit is not signed. See https://github.com/Ekumen-OS/andino/pull/230/checks?check_run_id=22870646833 for instructions on how to fix it.

On the other hand, I would appreciate it if you could use the PR description template, which is useful so as to avoid missing any important information (such as linking this PR to an issue).

Thanks!

**Comment by jballoffet** [comment]
On the other hand, how was this tested? Were you able to run the simulation? If so, I would appreciate it if you could attach a screenshot or gif where the changes can be depicted. Thanks!

**Review by francocipollone — APPROVED** [review]
LGTM!

**Comment by francocipollone** [comment]
> On the other hand, how was this tested? Were you able to run the simulation? If so, I would appreciate it if you could attach a screenshot or gif where the changes can be depicted. Thanks!

Adding to this: The change will be only noticed in the odometry calculation and velocity of the wheels. Not visual change here.

**Comment by francocipollone** [comment]
> @francocipollone I could add the output of an 'echo' in the odometry or velocity topics if you want

Not needed! LGTM for me . Thanks for contributing :smiley:

**Review by jballoffet — APPROVED** [review]
LGTM! Thanks @JesusSilvaUtrera for contributing to Andino!

**Pull request merged**
