### PR TITLE
Add andino_localization package with rf2o_laser_odometry algorithm

### PR DESCRIPTION
**Pull request by Hezhexi2002**
# 🎉 New feature

Closes #<NUMBER>

## Summary

This PR introduces a new localization package `andino_localization` to the Andino robot project, incorporating the `rf2o_laser_odometry` algorithm. This algorithm provides an efficient and accurate method for 2D odometry based on planar laser scans, particularly beneficial for mobile robots with less accurate wheel odometry. The `rf2o_laser_odometry` method performs dense scan alignment based on scan gradients, offering a robust alternative to traditional approaches that require correspondence searching.

### Changes Made:

- Added the `andino_localization` package with `rf2o_laser_odometry`.
- Integrated the `rf2o_laser_odometry` source files, launch files, and configuration.
- Updated `CMakeLists.txt` and `package.xml` to support the new package.
- Included example launch file for the new odometry algorithm.

## Test it

Follow the [`andino_navigation`'s README](./andino_navigation/README.md) instructions for bringing up the Navigation stack in the real robot or in the simulation.

## Checklist

- [x] Signed all commits for DCO
- [x]  Added tests
- [x]  Added example and/or tutorial
- [ ] Updated documentation (as needed)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by francocipollone** [comment]
@Hezhexi2002 First of all thanks a lot for contributing! 

Let me go over all the changes

**Comment by Hezhexi2002** [comment]
> Hey there @Hezhexi2002 , thanks a lot for trying to contribute to the andino project. It is indeed interesting.
> 
> We plan to keep this repository simple, and all new projects and features will be added in a separate repo. See that we have a [related projects section](https://github.com/Ekumen-OS/andino?tab=readme-ov-file#paperclips-related-projects). So I invite you to create a repository, create a ros2 package for provide this new `andino_localization` package. We will be happy to link it to the related projects section 🚀
> 
> Closing the PR
Hey there! 👋

Thanks for your feedback on my PR! I've tested the andino_localization package with a real 2D lidar, and it works. 🎉 However, I feel it's not quite ready to be a standalone "related project" yet.

The package is based on rf2o_laser_odometry with some modifications. While functional, it could use more andino-specific optimizations and features. 🛠️

I'm currently preparing for grad school exams 📚, so I can't dedicate much time to development right now. But I'm not abandoning the project!

After my exams, I plan to:
- Dive deeper into the algorithm
- Optimize it for andino
- Do more comprehensive testing
- Create solid documentation

I'm excited to contribute a more robust solution in the future. Thanks for your understanding! 🚀

**Comment by francocipollone** [comment]
> > Hey there @Hezhexi2002 , thanks a lot for trying to contribute to the andino project. It is indeed interesting.
> > We plan to keep this repository simple, and all new projects and features will be added in a separate repo. See that we have a [related projects section](https://github.com/Ekumen-OS/andino?tab=readme-ov-file#paperclips-related-projects). So I invite you to create a repository, create a ros2 package for provide this new `andino_localization` package. We will be happy to link it to the related projects section 🚀
> > Closing the PR
> > Hey there! 👋
> 
> Thanks for your feedback on my PR! I've tested the andino_localization package with a real 2D lidar, and it works. 🎉 However, I feel it's not quite ready to be a standalone "related project" yet.
> 
> The package is based on rf2o_laser_odometry with some modifications. While functional, it could use more andino-specific optimizations and features. 🛠️
> 
> I'm currently preparing for grad school exams 📚, so I can't dedicate much time to development right now. But I'm not abandoning the project!
> 
> After my exams, I plan to:
> 
> * Dive deeper into the algorithm
> * Optimize it for andino
> * Do more comprehensive testing
> * Create solid documentation
> 
> I'm excited to contribute a more robust solution in the future. Thanks for your understanding! 🚀

Wow that's great. Thanks a lot for your effort on contributing. Do not hesitate on pinging us in the future we can help you out with this, however as it is a great job you did it would be awesome if it is located in a repo under your profile, so you have all the credits. It is a great example on growing the community. We can help you out at that time to setup the repo, we also have a discord, feel free to give us a ping.

Looking forward to have this andino_localization package  with this localization variant up and running!

**Comment by Hezhexi2002** [comment]
> > > Hey there @Hezhexi2002 , thanks a lot for trying to contribute to the andino project. It is indeed interesting.
> > > We plan to keep this repository simple, and all new projects and features will be added in a separate repo. See that we have a [related projects section](https://github.com/Ekumen-OS/andino?tab=readme-ov-file#paperclips-related-projects). So I invite you to create a repository, create a ros2 package for provide this new `andino_localization` package. We will be happy to link it to the related projects section 🚀
> > > Closing the PR
> > > Hey there! 👋
> > 
> > 
> > Thanks for your feedback on my PR! I've tested the andino_localization package with a real 2D lidar, and it works. 🎉 However, I feel it's not quite ready to be a standalone "related project" yet.
> > The package is based on rf2o_laser_odometry with some modifications. While functional, it could use more andino-specific optimizations and features. 🛠️
> > I'm currently preparing for grad school exams 📚, so I can't dedicate much time to development right now. But I'm not abandoning the project!
> > After my exams, I plan to:
> > 
> > * Dive deeper into the algorithm
> > * Optimize it for andino
> > * Do more comprehensive testing
> > * Create solid documentation
> > 
> > I'm excited to contribute a more robust solution in the future. Thanks for your understanding! 🚀
> 
> Wow that's great. Thanks a lot for your effort on contributing. Do not hesitate on pinging us in the future we can help you out with this, however as it is a great job you did it would be awesome if it is located in a repo under your profile, so you have all the credits. It is a great example on growing the community. We can help you out at that time to setup the repo, we also have a discord, feel free to give us a ping.
> 
> Looking forward to have this andino_localization package with this localization variant up and running!

Thank you so much for your supportive response! 😊 I'm truly grateful for your encouragement and offer to help.

I really appreciate the suggestion to host the repo under my profile. It's a great idea, and I'm honored by the recognition. I'll definitely take you up on the offer to help set up the repo when the time comes.

It's fantastic to hear about the Discord community too. I'd love to join and connect with other contributors. Could you please share the Discord invite link?

I'm looking forward to working on the andino_localization package after my exams. Your support means a lot, and I'm excited to contribute to the andino community!

Thanks again for being so welcoming and supportive. I'll make sure to reach out when I'm ready to move forward with the project. 🚀

Best regards,
hezhexi2002

**Pull request closed without merging**
