### PR TITLE
Jazzy initial migration

### PR DESCRIPTION
**Pull request by JesusSilvaUtrera**
# 🎉 New feature

Closes ticket from Andino Internal

## Summary
Initial PR for the Jazzy migration, the workspace is being built correctly and I have removed the `andino_gz_classic` package. I also left a comment on `andino_apps` launch files to change the simulation from Gazebo classic to Gazebo Harmonic.

## Test it
Follow the instructions on `docker/README.md` to build and run the image, then install all the necessary dependencies with `rosdep` and build the workspace.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by JesusSilvaUtrera** [comment]
@francocipollone I need to fix the DCO, will do that tomorrow because right now I need to focus on something else, but I opened it JIC you want to take a look. We still need to decide if we are going to use the `ubuntu` user or do some kind of worakround.

**Review by jballoffet — CHANGES_REQUESTED** [review]
Thanks @JesusSilvaUtrera!

Please consider creating a first PR that removes the Gazebo Classic package on the Jazzy branch, so as to reduce the size of this PR and ease the review process. Thank you!

**Comment by JesusSilvaUtrera** [comment]
I thought it might be useful to rebase the brnach with humble directly and solve the conflicts to add the last changes, but maybe I messed it up for the review, I will try to see what to do or maybe we can approve it if no errors are found with the physical robot, I don't know.

**Comment by JesusSilvaUtrera** [comment]
@francocipollone I am going to close this to divide this PR in 2 smaller PRs after rebasing the `jazzy` branch on the original repo (thanks @jballoffet for the help).

**Pull request closed without merging**
